/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <zephyr.h>
#include <stdio.h>
#include <string.h>
#include "cmsis_os.h"
#include "hal_gpio.h"
#include "plat_gpio.h"
#include "plat_isr.h"

#define gpio_name_to_num(x) #x,
char *gpio_name[] = { name_gpio0 name_gpio1 name_gpio2 name_gpio3 name_gpio4 name_gpio5 name_gpio6
			      name_gpio7 name_gpio8 name_gpio9 name_gpioA name_gpioB name_gpioC
				      name_gpioD name_gpioE name_gpioF };
#undef gpio_name_to_num

void gpio_int_default()
{
	return;
}

// clang-format off
GPIO_CFG plat_gpio_cfg[] = {
	//  chip,      number,   is_init, is_latch, direction,    status,     property,    int_type,              int_cb
	// GPIO 0 group
	{ CHIP_GPIO, 0, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_EDGE_FALLING,
	  NULL },
	{ CHIP_GPIO, 1, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_EDGE_BOTH,
	  NULL },
	{ CHIP_GPIO, 2, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_EDGE_BOTH, NULL },
	{ CHIP_GPIO, 3, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 4, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 5, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_EDGE_BOTH,
	  ISR_GPIO_ALL_VR_PM_ALERT_R_N },
	{ CHIP_GPIO, 6, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_EDGE_FALLING,
	  NULL },
	{ CHIP_GPIO, 7, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_EDGE_BOTH,
	  NULL },
	// GPIO 1 group
	{ CHIP_GPIO, 8, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 9, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 10, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 11, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 12, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 13, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 14, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 15, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO 2 group
	{ CHIP_GPIO, 16, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 17, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 18, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 19, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 20, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 21, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 22, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 23, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	// GPIO 3 group
	{ CHIP_GPIO, 24, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 25, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 26, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 27, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 28, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 29, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 30, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 31, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO 4 group
	{ CHIP_GPIO, 32, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 33, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 34, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 35, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 36, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 37, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 38, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 39, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO 5 group
	{ CHIP_GPIO, 40, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 41, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 42, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 43, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 44, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 45, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 46, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 47, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	// GPIO 6 group
	{ CHIP_GPIO, 48, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 49, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 50, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 51, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 52, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 53, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 54, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 55, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO 7 group
	{ CHIP_GPIO, 56, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 57, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 58, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 59, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 60, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 61, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 62, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 63, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO 8 group
	{ CHIP_GPIO, 64, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 65, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 66, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 67, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 68, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 69, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 70, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 71, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO 9 group
	{ CHIP_GPIO, 72, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 73, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 74, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 75, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 76, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 77, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 78, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 79, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO A group
	{ CHIP_GPIO, 80, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 81, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 82, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 83, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 84, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL },
	{ CHIP_GPIO, 85, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 86, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 87, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO B group
	{ CHIP_GPIO, 88, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 89, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 90, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 91, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 92, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 93, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 94, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 95, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO C group
	{ CHIP_GPIO, 96, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 97, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 98, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 99, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 100, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 101, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 102, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 103, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO D group
	{ CHIP_GPIO, 104, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 105, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 106, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 107, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 108, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 109, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 110, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 111, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO E group
	{ CHIP_GPIO, 112, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 113, ENABLE, DISABLE, GPIO_INPUT, GPIO_HIGH, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 114, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 115, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 116, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 117, ENABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 118, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 119, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	// GPIO F group
	{ CHIP_GPIO, 120, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 121, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 122, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
	{ CHIP_GPIO, 123, DISABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE,
	  NULL },
};
// clang-format on

bool pal_load_gpio_config(void)
{
	memcpy(&gpio_cfg[0], &plat_gpio_cfg[0], sizeof(plat_gpio_cfg));
	return 1;
}

// clang-format off
/*
 * SGPIO real pin table (see plat_gpio.h for the name -> bit mapping and the
 * CPLD-vs-BIC direction note).
 *
 * IN pins (status/alert signals the BIC only reads) are ENABLE by default -
 * configuring an SGPIO input pin has no hardware side effect (see
 * sgpio_npcm4xx_config(): GPIO_INPUT alone touches no register), so there's
 * no risk in turning them all on up front.
 *
 * OUT pins (control/reset/strap/enable signals the BIC drives) are left
 * DISABLE - these actively drive real reset/strap/enable lines into Hamsa/
 * Zora/Owl, and the correct GPIO_HIGH/GPIO_LOW init value is a power-
 * sequencing decision, not something to default without the spec. Flip to
 * ENABLE and set "status" one at a time as each is confirmed safe.
 */
GPIO_CFG plat_sgpio_cfg[] = {
	//     chip,                     number, is_init, is_latch, direction,   status,   property,  int_type,           int_cb
	// SGPIO0_OUT (IOX1, BIC --> CPLD; table column "SGPIO0 Input")
	{ CHIP_SGPIO, wHAMSA_MFIO19, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 0
	{ CHIP_SGPIO, wZORA00_VQPS_TOP_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 1
	{ CHIP_SGPIO, wZORA01_VQPS_TOP_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 2
	{ CHIP_SGPIO, wZORA10_VQPS_TOP_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 3
	{ CHIP_SGPIO, wZORA11_VQPS_TOP_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 4
	{ CHIP_SGPIO, wZORA00_VQPS_U_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 5
	{ CHIP_SGPIO, wZORA01_VQPS_U_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 6
	{ CHIP_SGPIO, wZORA10_VQPS_U_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 7
	{ CHIP_SGPIO, wZORA11_VQPS_U_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 8
	{ CHIP_SGPIO, wHAMSA_VQPS_EFUSE_USER_EN, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 9
	{ CHIP_SGPIO, wHAMSA_TEST_STRAP_R, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 10
	{ CHIP_SGPIO, wHAMSA_LS_STRAP0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 11
	{ CHIP_SGPIO, wHAMSA_LS_STRAP1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 12
	{ CHIP_SGPIO, wHAMSA_CRM_STRAP0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 13
	{ CHIP_SGPIO, wHAMSA_CRM_STRAP1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 14
	{ CHIP_SGPIO, wHAMSA_MFIO7, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 15
	{ CHIP_SGPIO, wHAMSA_MFIO9, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 16
	{ CHIP_SGPIO, wHAMSA_MFIO11, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 17
	{ CHIP_SGPIO, wHAMSA_MFIO14, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 18
	{ CHIP_SGPIO, wHAMSA_MFIO16, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 19
	{ CHIP_SGPIO, wHAMSA_MFIO17, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 20
	{ CHIP_SGPIO, wHAMSA_MFIO18, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 21
	{ CHIP_SGPIO, wHAMSA_MFIO22, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 22
	{ CHIP_SGPIO, wHAMSA_MFIO23, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 23
	{ CHIP_SGPIO, wHAMSA_MFIO25, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 24
	{ CHIP_SGPIO, wHAMSA_CORE_TAP_CTRL_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 25
	{ CHIP_SGPIO, wHAMSA_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 26
	{ CHIP_SGPIO, wHAMSA_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 27
	{ CHIP_SGPIO, wHAMSA_DFT_TAP_EN_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 28
	{ CHIP_SGPIO, wFM_JTAG_HAMSA_JTCE0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 29
	{ CHIP_SGPIO, wFM_JTAG_HAMSA_JTCE1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 30
	{ CHIP_SGPIO, wFM_JTAG_HAMSA_JTCE2, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 31
	{ CHIP_SGPIO, wFM_JTAG_HAMSA_JTCE3, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 32
	{ CHIP_SGPIO, wZORA00_TEST_STRAP, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 33
	{ CHIP_SGPIO, wZORA01_TEST_STRAP, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 34
	{ CHIP_SGPIO, wZORA10_TEST_STRAP, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 35
	{ CHIP_SGPIO, wZORA11_TEST_STRAP, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 36
	{ CHIP_SGPIO, wZORA00_CRM_STRAP0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 37
	{ CHIP_SGPIO, wZORA01_CRM_STRAP0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 38
	{ CHIP_SGPIO, wZORA10_CRM_STRAP0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 39
	{ CHIP_SGPIO, wZORA11_CRM_STRAP0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 40
	{ CHIP_SGPIO, wZORA00_CRM_STRAP1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 41
	{ CHIP_SGPIO, wZORA01_CRM_STRAP1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 42
	{ CHIP_SGPIO, wZORA10_CRM_STRAP1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 43
	{ CHIP_SGPIO, wZORA11_CRM_STRAP1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 44
	{ CHIP_SGPIO, wZORA00_CORE_TAP_CTRL_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 45
	{ CHIP_SGPIO, wZORA01_CORE_TAP_CTRL_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 46
	{ CHIP_SGPIO, wZORA10_CORE_TAP_CTRL_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 47
	{ CHIP_SGPIO, wZORA11_CORE_TAP_CTRL_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 48
	{ CHIP_SGPIO, wZORA00_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 49
	{ CHIP_SGPIO, wZORA01_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 50
	{ CHIP_SGPIO, wZORA10_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 51
	{ CHIP_SGPIO, wZORA11_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 52
	{ CHIP_SGPIO, wZORA00_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 53
	{ CHIP_SGPIO, wZORA01_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 54
	{ CHIP_SGPIO, wZORA10_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 55
	{ CHIP_SGPIO, wZORA11_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 56
	{ CHIP_SGPIO, wZORA00_DFT_TAP_EN_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 57
	{ CHIP_SGPIO, wZORA01_DFT_TAP_EN_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 58
	{ CHIP_SGPIO, wZORA10_DFT_TAP_EN_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 59
	{ CHIP_SGPIO, wZORA11_DFT_TAP_EN_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 60
	{ CHIP_SGPIO, wFM_JTAG_ZORA00_JTCE0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 61
	{ CHIP_SGPIO, wFM_JTAG_ZORA00_JTCE1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 62
	{ CHIP_SGPIO, wFM_JTAG_ZORA00_JTCE2, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 63
	// SGPIO0_IN (IOX1, CPLD --> BIC; table column "SGPIO0 Output")
	{ CHIP_SGPIO, SMB_ZORA00_CRM_LS_LVC33_ALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 0
	{ CHIP_SGPIO, SMB_ZORA01_CRM_LS_LVC33_ALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 1
	{ CHIP_SGPIO, SMB_ZORA10_CRM_LS_LVC33_ALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 2
	{ CHIP_SGPIO, SMB_ZORA11_CRM_LS_LVC33_ALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 3
	{ CHIP_SGPIO, FM_MODULE_PWRBRK_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 4
	{ CHIP_SGPIO, IRQ_TMP75_1_ALERT_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 5
	{ CHIP_SGPIO, IRQ_TMP75_2_ALERT_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 6
	{ CHIP_SGPIO, IRQ_TMP75_3_ALERT_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 7
	{ CHIP_SGPIO, TEMP_MON2_OVERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 8
	{ CHIP_SGPIO, TEMP_MON3_OVERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 9
	{ CHIP_SGPIO, TEMP_MON4_OVERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 10
	{ CHIP_SGPIO, TEMP_MON5_OVERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 11
	{ CHIP_SGPIO, ZORA00_VDD_SMBALERT_N_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 12
	{ CHIP_SGPIO, ZORA01_VDD_SMBALERT_N_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 13
	{ CHIP_SGPIO, ZORA10_VDD_SMBALERT_N_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 14
	{ CHIP_SGPIO, ZORA11_VDD_SMBALERT_N_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 15
	{ CHIP_SGPIO, MAX_EW2_VDD_SMBALERT_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 16
	{ CHIP_SGPIO, MAX_EW1_VDD_SMBALERT_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 17
	{ CHIP_SGPIO, OWL_W_VDD_SMBALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 18
	{ CHIP_SGPIO, OWL_E_VDD_SMBALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 19
	{ CHIP_SGPIO, VDDPHY_HBM2367_SMBALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 20
	{ CHIP_SGPIO, VDDPHY_HBM0145_SMBALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 21
	{ CHIP_SGPIO, VDDC_HBM2367_SMBALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 22
	{ CHIP_SGPIO, SMB_HAMSA_LS_LVC33_ALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 23
	{ CHIP_SGPIO, RADSOK_CONN_PRSNT, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 24
	{ CHIP_SGPIO, CHASSIS1_LEAK_Q_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 25
	{ CHIP_SGPIO, LEAK1_DETECT, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 26
	{ CHIP_SGPIO, PRSNT_CHASSIS1_LEAK_CABLE_R_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 27
	{ CHIP_SGPIO, VDDC_HBM0145_SMBALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 28
	{ CHIP_SGPIO, SMB_VPP_HBM_P1V8_ALERT_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 29
	{ CHIP_SGPIO, VRHOT_ZORA00_VDD_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 30
	{ CHIP_SGPIO, VRHOT_ZORA01_VDD_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 31
	{ CHIP_SGPIO, VRHOT_ZORA10_VDD_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 32
	{ CHIP_SGPIO, VRHOT_ZORA11_VDD_N, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 33
	{ CHIP_SGPIO, ZORA00_STANDALONE_MODE_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 34
	{ CHIP_SGPIO, ZORA01_STANDALONE_MODE_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 35
	{ CHIP_SGPIO, ZORA10_STANDALONE_MODE_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 36
	{ CHIP_SGPIO, ZORA11_STANDALONE_MODE_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 37
	{ CHIP_SGPIO, ZORA00_HBM_CATTRIP_ALARM_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 38
	{ CHIP_SGPIO, ZORA01_HBM_CATTRIP_ALARM_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 39
	{ CHIP_SGPIO, ZORA10_HBM_CATTRIP_ALARM_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 40
	{ CHIP_SGPIO, ZORA11_HBM_CATTRIP_ALARM_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 41
	{ CHIP_SGPIO, HAMSA_CATTRIP_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 42
	{ CHIP_SGPIO, OWL_E_SOC_CATTRIP_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 43
	{ CHIP_SGPIO, OWL_W_SOC_CATTRIP_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 44
	{ CHIP_SGPIO, OWL_W_SOC_CATTRIP_R_BIT45, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 45
	{ CHIP_SGPIO, CLK_RDY_RC38208_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 46
	{ CHIP_SGPIO, HOST_PWRGD_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 47
	// SGPIO1_OUT (IOX2, BIC --> CPLD; table column "SGPIO1 Input")
	{ CHIP_SGPIO, wMMC_HAMSA_POWER_ON_RESET_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 0
	{ CHIP_SGPIO, wMMC_ZORA00_POWER_ON_RESET_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 1
	{ CHIP_SGPIO, wMMC_ZORA01_POWER_ON_RESET_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 2
	{ CHIP_SGPIO, wMMC_ZORA10_POWER_ON_RESET_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 3
	{ CHIP_SGPIO, wMMC_ZORA11_POWER_ON_RESET_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 4
	{ CHIP_SGPIO, wMMC_HAMSA_SYS_RST_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 5
	{ CHIP_SGPIO, wMMC_ZORA00_SYS_RST_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 6
	{ CHIP_SGPIO, wMMC_ZORA01_SYS_RST_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 7
	{ CHIP_SGPIO, wMMC_ZORA10_SYS_RST_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 8
	{ CHIP_SGPIO, wMMC_ZORA11_SYS_RST_PLD_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 9
	{ CHIP_SGPIO, ZORA00_PWR_CAP_LV1_PLD, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 41
	{ CHIP_SGPIO, ZORA00_PWR_CAP_LV2_PLD, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 42
	{ CHIP_SGPIO, ZORA00_PWR_CAP_LV3_PLD, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 43
	{ CHIP_SGPIO, ZORA_PWR_CAP_LV1_PLD, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 44
	{ CHIP_SGPIO, ZORA_PWR_CAP_LV2_PLD, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 45
	{ CHIP_SGPIO, ZORA_PWR_CAP_LV3_PLD, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 46
	{ CHIP_SGPIO, wPLD_OWL_E_DFT_TAP_EN_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 47
	{ CHIP_SGPIO, wPLD_OWL_E_CORE_TAP_CTRL_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 48
	{ CHIP_SGPIO, wPLD_OWL_E_PAD_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 49
	{ CHIP_SGPIO, wPLD_OWL_E_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 50
	{ CHIP_SGPIO, wPLD_OWL_W_DFT_TAP_EN_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 51
	{ CHIP_SGPIO, wPLD_OWL_W_CORE_TAP_CTRL_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 52
	{ CHIP_SGPIO, wPLD_OWL_W_PAD_TRI_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 53
	{ CHIP_SGPIO, wPLD_OWL_W_ATPG_MODE_L, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 54
	{ CHIP_SGPIO, wFM_JTAG_ZORA01_JTCE0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 55
	{ CHIP_SGPIO, wFM_JTAG_ZORA01_JTCE1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 56
	{ CHIP_SGPIO, wFM_JTAG_ZORA01_JTCE2, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 57
	{ CHIP_SGPIO, wFM_JTAG_ZORA10_JTCE0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 58
	{ CHIP_SGPIO, wFM_JTAG_ZORA10_JTCE1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 59
	{ CHIP_SGPIO, wFM_JTAG_ZORA10_JTCE2, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 60
	{ CHIP_SGPIO, wFM_JTAG_ZORA11_JTCE0, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 61
	{ CHIP_SGPIO, wFM_JTAG_ZORA11_JTCE1, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 62
	{ CHIP_SGPIO, wFM_JTAG_ZORA11_JTCE2, DISABLE, DISABLE, GPIO_OUTPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 63
	// SGPIO1_IN (IOX2, CPLD --> BIC; table column "SGPIO1 Output")
	{ CHIP_SGPIO, FM_52V_PWROFF_SENSE_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 0
	{ CHIP_SGPIO, FM_3V3_PWROFF_SENSE_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 1
	{ CHIP_SGPIO, PWRGD_P1V8_AUX, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 2
	{ CHIP_SGPIO, PWRGD_P1V2_AUX, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 3
	{ CHIP_SGPIO, PWR_EN, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 4
	{ CHIP_SGPIO, P12V_UBC1_PWRGD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 5
	{ CHIP_SGPIO, P12V_UBC2_PWRGD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 6
	{ CHIP_SGPIO, PWRGD_P3V3_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 7
	{ CHIP_SGPIO, PWRGD_P4V2_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 8
	{ CHIP_SGPIO, PWRGD_U677, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 9
	{ CHIP_SGPIO, PWRGD_U678, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 10
	{ CHIP_SGPIO, PWRGD_U682, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 11
	{ CHIP_SGPIO, PWRGD_P5V_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 12
	{ CHIP_SGPIO, PWRGD_LDO_IN_1V2_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 13
	{ CHIP_SGPIO, PWRGD_P1V8_BF_R2, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 14
	{ CHIP_SGPIO, PWRGD_P0V75_AVDD_HCSL_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 15
	{ CHIP_SGPIO, PWRGD_HAMSA_VDD_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 16
	{ CHIP_SGPIO, PWRGD_OWL_W_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 17
	{ CHIP_SGPIO, PWRGD_OWL_E_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 18
	{ CHIP_SGPIO, PWRGD_MAX_EW2_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 19
	{ CHIP_SGPIO, PWRGD_MAX_EW1_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 20
	{ CHIP_SGPIO, PWRGD_MAX_N_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 21
	{ CHIP_SGPIO, PWRGD_MAX_M_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 22
	{ CHIP_SGPIO, PWRGD_MAX_S_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 23
	{ CHIP_SGPIO, PWRGD_OWL_E_TRVDD0P75_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 24
	{ CHIP_SGPIO, PWRGD_OWL_W_TRVDD0P75_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 25
	{ CHIP_SGPIO, PWRGD_VDDPHY_HBM0145_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 26
	{ CHIP_SGPIO, PWRGD_VDDPHY_HBM2367_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 27
	{ CHIP_SGPIO, PWRGD_ZORA00_VDDL_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 28
	{ CHIP_SGPIO, PWRGD_ZORA01_VDDL_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 29
	{ CHIP_SGPIO, PWRGD_ZORA10_VDDL_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 30
	{ CHIP_SGPIO, PWRGD_ZORA11_VDDL_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 31
	{ CHIP_SGPIO, PWRGD_ZORA00_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 32
	{ CHIP_SGPIO, PWRGD_ZORA01_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 33
	{ CHIP_SGPIO, PWRGD_ZORA10_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 34
	{ CHIP_SGPIO, PWRGD_ZORA11_VDD_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 35
	{ CHIP_SGPIO, PWRGD_P1V5_PLL_VDDA_OWL_E, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 36
	{ CHIP_SGPIO, PWRGD_P1V5_PLL_VDDA_OWL_W, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 37
	{ CHIP_SGPIO, PWRGD_P1V5_PLL_VDDA_SOC, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 38
	{ CHIP_SGPIO, PWRGD_P1V2_PLL_VDDA_OWL_W, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 39
	{ CHIP_SGPIO, PWRGD_VPP_HBM2367_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 40
	{ CHIP_SGPIO, PWRGD_VPP_HBM0145_R, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 41
	{ CHIP_SGPIO, PWRGD_VDDC_HBM0145, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 42
	{ CHIP_SGPIO, PWRGD_VDDC_HBM2367_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 43
	{ CHIP_SGPIO, PWRGD_VDDQ_HBM0145_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 44
	{ CHIP_SGPIO, PWRGD_VDDQ_HBM2367_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 45
	{ CHIP_SGPIO, PWRGD_VDDQL_HBM0145_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 46
	{ CHIP_SGPIO, PWRGD_VDDQL_HBM2367_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 47
	{ CHIP_SGPIO, PWRGD_HAMSA_AVDD_PCIE_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 48
	{ CHIP_SGPIO, PWRGD_OWL_E_TRVDD0P9_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 49
	{ CHIP_SGPIO, PWRGD_OWL_W_TRVDD0P9_PLD, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 50
	{ CHIP_SGPIO, PWRGD_PVDD1P5, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 51
	{ CHIP_SGPIO, PWRGD_HAMSA_VDDHRXTX_PCIE3, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 52
	{ CHIP_SGPIO, PWRGD_HAMSA_VDDHRXTX_PCIE2, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 53
	{ CHIP_SGPIO, PWRGD_HAMSA_VDDHRXTX_PCIE1, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 54
	{ CHIP_SGPIO, PWRGD_HAMSA_VDDHRXTX_PCIE0, ENABLE, DISABLE, GPIO_INPUT, GPIO_LOW, PUSH_PULL, GPIO_INT_DISABLE, NULL }, // bit 55
};
// clang-format on

bool pal_load_sgpio_config(void)
{
	memcpy(&sgpio_cfg[0], &plat_sgpio_cfg[0], sizeof(plat_sgpio_cfg));
	return 1;
};
